export const PERSONA_CONFIG = {
  ed: {
    id: 'ed',
    name: 'Ed',
    fullName: 'Ed',
    role: 'The Encourager',
    description: 'Big heart, bigger enthusiasm. Ed celebrates every step you take and turns mistakes into "AWESOME learning moments!"',
    color: '#E8A317',
    bgColor: '#FFF4D6',
    borderColor: '#E8A317',
    textColor: '#7A4800',
    hat: null,
    quirk: 'Loves gravy, buttered toast & monster movies 🐔',
    catchphrase: '"I love chickens!"',
    emoji: '🐔',
    // SVG character silhouette accent color
    accent: '#E8A317',
  },
  edd: {
    id: 'edd',
    name: 'Edd',
    fullName: 'Edd (Double D)',
    role: 'The Scholar',
    description: 'Precise, patient, and thorough. Double D explains grammar rules properly so you understand the WHY, not just the what.',
    color: '#4A90D9',
    bgColor: '#E8F2FF',
    borderColor: '#4A90D9',
    textColor: '#0A3A6B',
    hat: 'black beanie',
    quirk: 'Labels everything & adores scientific order ⛰',
    catchphrase: '"According to my calculations..."',
    emoji: '⛰',
    accent: '#4A90D9',
  },
  eddy: {
    id: 'eddy',
    name: 'Eddy',
    fullName: 'Eddy',
    role: 'The Street-Smart',
    description: "Fast-talking and sharp. Eddy teaches you real English — slang, idioms, how people ACTUALLY talk on the street.",
    color: '#E84040',
    bgColor: '#FFE8E8',
    borderColor: '#E84040',
    textColor: '#7A0000',
    hat: null,
    quirk: 'Always cooking a scheme for jawbreakers 💰',
    catchphrase: '"I\'ve got a scam!"',
    emoji: '💰',
    accent: '#E84040',
  },
};

export const PERSONA_ORDER = ['ed', 'edd', 'eddy'];
